#!/bin/sh -e

default_prepare
autoreconf -fi

./configure \
	--build=$CBUILD \
	--host=$CHOST \
	--prefix=/usr \
	--sysconfdir=/etc \
	--mandir=/usr/share/man \
	--localstatedir=/var

make
make DESTDIR="$1" install
