#!/bin/sh -e


./configure \
	--build=$CBUILD \
	--host=$CHOST \
	--prefix=/usr \
	--sysconfdir=/etc \
	--mandir=/usr/share/man \
	--infodir=/usr/share/info \
	--localstatedir=/var

make -j1 lib-ext
make -j1 all

make DESTDIR="$1" install
