#!/bin/sh -e

./configure \
	--prefix=/usr \
	--sysconfdir=/etc \
	--mandir=/usr/share/man \
	--infodir=/usr/share/info \
	--localstatedir=/var

make -j1 lib-ext
make -j1 all
make DESTDIR="$1" install

install -Dm644 LICENSE "$1"/usr/share/lisences/opam/LICENSE"
