#!/bin/sh -e

# Disable warning as CFLAGS must work this way.
# shellcheck disable=2086

export AS="cc -c"
export ASPP="cc -c"

make cold CONFIGURE_ARGS="--prefix=/usr --disable-werror"

make cold-install
make DESTDIR="$1" install
