#!/bin/sh -e

patch -p0 < rpath.patch

make

install -Dm644 src/dictionary.h "$1/usr/include/dictionary.h"
install -Dm644 src/iniparser.h "$1/usr/include/iniparser.h"
install -Dm755 libiniparser.so.1 "$1/usr/lib/libiniparser.so.1"

ln -s libiniparser.so.1 "$1/usr/lib/libiniparser.so"
